version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: lazysizes
    versions:
    - 5.3.1
  - dependency-name: "@hpcc-js/wasm"
    versions:
    - 1.2.0
    - 1.2.1
    - 1.3.0
    - 1.4.1
  - dependency-name: marked
    versions:
    - 1.2.8
