# we use fingerprinting so we can cache
[[headers]]
  for = "*.js" # js files should be set this way
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "*.css" # css files too
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[build]
  publish = "public"
  command = "hugo --gc --minify"

  [build.environment]
    HUGO_VERSION = "0.118.2"

[context.production.environment]
  HUGO_ENV           = "production"
  HUGO_ENABLEGITINFO = "true"

[context.split1]
  command = "hugo --gc --minify --enableGitInfo"

  [context.split1.environment]
    HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.next.environment]
  HUGO_ENABLEGITINFO = "true"
